" $Id: vimrc,v 1.3 2007/11/23 13:03:39 verhoef Exp $

" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set autoindent		" always set autoindenting on
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching

" Don't use Ex mode, use Q for formatting
map Q gq

" Make p in Visual mode replace the selected text with the "" register.
vnoremap p <Esc>:let current_reg = @"<CR>gvs<C-R>=current_reg<CR><Esc>

" Tell vim that our terminal supports many, many colors
set t_Co=256

" works best so far
let &t_Sf="\e[3%p1%dm"
let &t_Sb="\e[4%p1%dm"

" does not work completely
"let &t_Sf="\e[3%dm"
"let &t_Sb="\e[4%dm"

" does not work
"let &t_Sf="[38;5;%dm"
"let &t_Sb="[48;5;%dm"


" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " do not insert comment sign after a new line
  autocmd FileType * setlocal formatoptions-=o

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

endif " has("autocmd")

" personal preferences
set nobackup
set ff=unix

" set foldmethod=marker
" set foldcolumn=4

set tabstop=2
set shiftwidth=2
set expandtab

set wrap
"set linebreak
"set showbreak=\ ->\ 

colorscheme desert256
"set guifont=Lucida_Console:h9:cANSI
"au GUIEnter * simalt ~x

"let is_kornshell=1

